const data = {
  products: [
    {
      id: 1,
      title: 'Shirt Small',
      slug: 'shirt-small',
      img: '/images/shirt7.jpg',
      brand: 'adidas',
      numreviews: 8,
      countInStock: 16,
      desc: 'desc of product',
      price: 1600,
      rating: 4.3,
    },
    {
      id: 2,
      title: 'Product',
      slug: 'shirt-large',
      img: '/images/shirt2.jpg',
      brand: 'adidas',
      numreviews: 8,
      countInStock: 16,
      desc: 'desc of product',
      price: 1600,
      rating: 4.3,
    },
    {
      id: 3,
      title: 'Product',
      slug: 'shirt-mini',
      img: '/images/shirt5.jpg',
      brand: 'adidas',
      numreviews: 8,
      countInStock: 16,
      desc: 'desc of product',
      price: 1600,
      rating: 4.3,
    },
    {
      id: 4,
      title: 'Product',
      slug: 'shirt-lengthy',
      img: '/images/shirt4.jpg',
      brand: 'adidas',
      numreviews: 8,
      countInStock: 16,
      desc: 'desc of product',
      price: 1600,
      rating: 4.3,
    },
    {
      id: 5,
      title: 'Product',
      slug: 'shirt-multi',
      img: '/images/shirt5.jpg',
      brand: 'adidas',
      numreviews: 8,
      countInStock: 16,
      desc: 'desc of product',
      price: 1600,
      rating: 4.3,
    },
    {
      id: 6,
      title: 'Product',
      slug: 'shirt-macro',
      img: '/images/shirt6.jpg',
      brand: 'adidas',
      numreviews: 8,
      countInStock: 16,
      desc: 'desc of product',
      price: 1600,
      rating: 4.3,
    },
  ],
};

export default data;
